import type { Metadata } from "next";
import { Nav } from "@/components/marketing/Nav";
import { Footer } from "@/components/marketing/Footer";
import { Eyebrow, Slide } from "@/components/marketing/primitives";
import { DISCLAIMER } from "@/lib/constants";

export const metadata: Metadata = {
  title: "Legal — Capital Investment Prospects",
  description:
    "CIP is a research and simulation tool. Not a broker, not investment advice, no live execution.",
};

const SECTIONS = [
  [
    "Not investment advice",
    "CIP is an educational and research tool. Nothing it produces is a recommendation to buy, sell, or hold any instrument, and nothing on this site should be read as personalised financial advice. We are not a licensed investment adviser. Decisions about your money are yours, and you should consult a qualified professional before making them.",
  ],
  [
    "Not a broker — paper only",
    "CIP does not execute orders, hold funds, or connect to any brokerage or exchange for the purpose of trading. Live execution is not implemented in the product. Every position, fill, and result you see is simulated against real market data.",
  ],
  [
    "Simulated results",
    "Figures produced by the pipeline are the output of models run over historical and current market data. They are labelled SIMULATED wherever they appear. Simulated results have inherent limitations: they benefit from hindsight, they cannot fully reproduce liquidity and market impact, and they do not represent actual trading. Past performance does not guarantee future results.",
  ],
  [
    "Market data",
    "Market data is supplied by third parties, including Binance and Polygon.io, and is used for research and simulation. It may be delayed, incomplete, or revised. Where a data source is unavailable, CIP substitutes clearly-badged sample data rather than presenting an unmarked estimate.",
  ],
  [
    "AI-generated language",
    "Written explanations in the product are generated by a large language model. The model is given the figures the engine computed and asked to describe them; it does not produce, estimate, or alter any number. Language can still be imperfect — the underlying computed figures are the record.",
  ],
  [
    "No warranty",
    "The service is provided “as is”, without warranty of any kind. To the fullest extent permitted by law, we accept no liability for any loss arising from use of, or reliance on, this site or the product.",
  ],
  [
    "Privacy",
    "The marketing site sets no advertising or tracking cookies. The prototype sends only your chosen market, asset, and timeframe to our server in order to compute an analysis; it does not require an account. If you email us, we keep that correspondence in order to reply to you.",
  ],
] as const;

export default function LegalPage() {
  return (
    <>
      <Nav />
      <main className="pt-[68px]">
        <Slide>
          <Eyebrow>Legal</Eyebrow>
          <h1 className="display mt-7">Terms, risk and disclosure</h1>

          <p className="mt-10 max-w-[70ch] border-l-2 border-signal pl-6 text-[16px] leading-relaxed text-[#d4d4d4]">
            {DISCLAIMER}
          </p>

          <div className="mt-16 max-w-[74ch] space-y-12">
            {SECTIONS.map(([title, body]) => (
              <section key={title}>
                <h2 className="text-[20px] font-medium">{title}</h2>
                <p className="mt-4 text-[16px] leading-[1.72] text-[#b4b4b4]">
                  {body}
                </p>
              </section>
            ))}
          </div>

          <p className="mt-16 border-t border-hairline pt-8 text-[13px] text-muted-2">
            This page describes the product’s posture in plain language. It is
            not a substitute for the definitive terms that will accompany a
            commercial launch.
          </p>
        </Slide>
      </main>
      <Footer />
    </>
  );
}
